#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


echo "⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼"
echo "🐙🐙🐙 RUN AS : $(date +%d/%m/%Y-%H:%M:%S) 🐙🐙🐙"
echo "⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼"
echo "👮☁️  Styling, linting, testing and building your project before committing [Pre-Push]
";



pnpm lint ||
(
        echo '😤🏀👋😤 Get that weak shit out of here! 😤🏀👋😤 
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)



# If everything passes... Now we can commit
echo '🚀🚀🚀🚀 You win this time... I am pushed this now. 🚀'
echo "🐙🐙🐙 FINISH AT : $(date +%d/%m/%Y-%H:%M:%S) 🐙🐙🐙"
echo "⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼"
