#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🧼 Start !!!!!"


# Format code.
echo "🛀 Formating code ... "
yarn format

# Check Prettier standards  
echo "🧹Checking"
yarn check-format ||

(
    echo '🤢🤮🤢🤮 Its FOKING RAW - Your styling looks disgusting. 🤢🤮🤢🤮
            Prettier Check Failed. Run [yarn format], add changes and try commit again.';
    false;
)

